name: common_dependencies
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_mobx: ^2.0.6+4
  flutter_modular: ^5.0.3
  mobx: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  mobx_codegen: ^2.0.7+3
  modular_test: ^2.0.0


flutter:
